# -*- coding: utf-8 -*-
"""CodeChef.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/swathi023/CodeChef-Solutions/blob/main/CodeChef.ipynb
"""

# Day 1: Python Basics
Topics Covered:
- Output and Print
- Variables and Data Types

# Output and Print in Python
#Learning how to display output using print()

# Basic print
print("Hello World")

# Multiple lines
print("Hello")
print("Swathi")

# Using newline
print("Hello\nWorld")

# Multiple values
print("My age is", 20)

# Variables and Data Types
#Introduction to storing data in Python

# Variables
name = "Swathi"
age = 20
height = 5.3

print(name, age, height)

# Data types
print(type(name))   # str
print(type(age))    # int
print(type(height)) # float